# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-30 17:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_aothor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='aothor',
            new_name='author',
        ),
    ]
